POST http://localhost:8080/api/cards
Content-Type: application/json

{"id":"c_0-20v-154hp-7278","manufacturer":"Fiat","type":"Coupe 2.0 20V","year":1993,"country":"N/A","doors":2,"body":"Coupe","seats":4,"driveWheel":"FWD","fuelType":"Petrol","fuelTankCapacity":63,"engineCapacity":1998,"powerKW":114,"powerHP":154,"maxTorque":186,"topSpeed":215,"acceleration":8.4,"weight":1270,"length":4250,"width":1768,"height":1355,"groundClearance":-1,"abs":"yes","tractionControl":"N/A","imageUrl":"assets/img/cars/fiat-coupe-fa-175-2.0-20v-154hp-7278.webp","logoURL":"assets/img/cars/logos/","carPageUrl":"https://www.auto-data.net/en/fiat-coupe-fa-175-2.0-20v-154hp-7278","objectPositionHorizontal":"","objectPositionVertical":"","objectWidth":"100%","objectHeight":"100%","gear1st":-1.0,"gear2nd":-1.0,"gear3rd":-1.0,"gear4th":-1.0,"gear5th":-1.0,"gear6th":-1.0,"finalDrive":-1.0}

###
PUT http://localhost:8080/api/cards
Content-Type: application/json

{
    "id": "2007_audi_a4_71215",
    "year": 2017
}

###
PUT http://localhost:8080/api/cards/2007_audi_a4_71215
Content-Type: application/json

{
    "id": "2007_audi_a4_71215",
    "objectPositionVertical": "3rem"
}

###
DELETE http://localhost:8080/api/cards/c_0-20v-154hp-7278
Content-Type: application/json


###
GET http://localhost:8080/api/cards
Accept: application/json


###
POST http://localhost:8080/api/cards/find
Content-Type: application/json

{
"manufacturer": "volvo"
}

###
POST http://localhost:8080/api/cards/uploadfile/updatecards
Accept: application/json

###
